<?php

return [
    'settings_nav' => [
        [
            'label' => 'App & Branding',
            'icon' => 'fa-solid fa-palette',
            'route' => 'settings.index',
            'params' => ['tab' => 'settings-app'],
            'permission' => 'view settings',
            'active_route' => 'settings.index',
            'match_query' => 'tab=settings-app',
        ],
        [
            'label' => 'Users',
            'icon' => 'fa-solid fa-users',
            'route' => 'settings.users.index',
            'params' => [],
            'permission' => 'view users',
            'active_route' => 'settings.users.*',
        ],
        [
            'label' => 'Media Library',
            'icon' => 'fa-solid fa-photo-film',
            'route' => 'settings.media.index',
            'params' => [],
            'permission' => 'view settings',
            'active_route' => 'settings.media.*',
        ],
        [
            'label' => 'Roles & Access',
            'icon' => 'fa-solid fa-user-lock',
            'route' => 'settings.rbac',
            'params' => [],
            'permission' => 'manage settings',
            'active_route' => 'settings.rbac*',
        ],
        [
            'label' => 'Activity',
            'icon' => 'fa-solid fa-chart-line',
            'route' => 'settings.index',
            'params' => ['tab' => 'settings-activity'],
            'permission' => 'view settings',
            'active_route' => 'settings.index',
            'match_query' => 'tab=settings-activity',
        ],
        [
            'label' => 'Security',
            'icon' => 'fa-solid fa-user-shield',
            'route' => 'settings.index',
            'params' => ['tab' => 'settings-security'],
            'permission' => 'view settings',
            'active_route' => 'settings.index',
            'match_query' => 'tab=settings-security',
        ],
        [
            'label' => 'Notifications',
            'icon' => 'fa-solid fa-bell',
            'route' => 'settings.index',
            'params' => ['tab' => 'settings-notifications'],
            'permission' => 'view settings',
            'active_route' => 'settings.index',
            'match_query' => 'tab=settings-notifications',
        ],
        [
            'label' => 'System Config',
            'icon' => 'fa-solid fa-gear',
            'route' => 'settings.index',
            'params' => ['tab' => 'settings-system'],
            'permission' => 'manage settings',
            'active_route' => 'settings.index',
            'match_query' => 'tab=settings-system',
        ],
    ],
];
